### ISSUE TITLE
cant find some files that the project requires

### ISSUE THREAD

**Issue by rajbirsinghit** [jakemmarsh/neural-network-stock-predictor#1]
hello, 
great work, going through the readme file i successfully set up the flask project, but running the app gave errors that hint that a file (public/js/lib/d3.js) is required for the project to run appropriately and is missing.
I am studying applications of neural nets in the field of finance, so your project can really help me.
Can you please provide the required file.
Thanks

**Comment by jakemmarsh** [comment]
It looks like the entire `public/js/lib` directory is missing, which is a problem. You should be aware that this project is sorely outdated.

I've just pushed some updates so that it should now have all of the dependencies you need after running `npm install`. The application should then be able to be built and started running `npm start`. I have not fully tested this, though.
